const organizer: any[] = [
  {
    id: 1,
    name: "Avik Agarwala",
    image: "",
    role: "Lead Organizer",
    linedin: "",
    twitter: "",
  },
  {
    id: 2,
    name: "Sagnik Bhattacharya",
    image: "",
    role: "Co-Organizer",
    linedin: "",
    twitter: "",
  },
  {
    id: 3,
    name: "Alik Agarwala",
    image: "",
    role: "Co-Organizer",
    linedin: "",
    twitter: "",
  },
  {
    id: 4,
    name: "Palash Das",
    image: "",
    role: "Co-Organizer & Tech Lead",
    linedin: "",
    twitter: "",
  },
];

const leads: any[] = [
  ,
  {
    id: 1,
    name: "Rajdeep Banerjee",
    image: "",
    role: "Co-Tech Lead",
    linedin: "",
    twitter: "",
  },
  {
    id: 2,
    name: "Rajdeep De",
    image: "",
    role: "Management Lead",
    linedin: "",
    twitter: "",
  },
  {
    id: 3,
    name: "Soumarghya Dhara",
    image: "",
    role: "Graphics Lead",
    linedin: "",
    twitter: "",
  },
  {
    id: 4,
    name: "Shreya Chatterjee",
    image: "",
    role: "Content Lead",
    linedin: "",
    twitter: "",
  },
  {
    id: 5,
    name: "Ankika Dey",
    image: "",
    role: "Treasurer",
    linedin: "",
    twitter: "",
  },
  {
    id: 6,
    name: "Soumyadeep Banejee",
    image: "",
    role: "Treasurer",
    linedin: "",
    twitter: "",
  },
  {
    id: 7,
    name: "Sauptik Roy",
    image: "",
    role: "Sponsorship Lead",
    linedin: "",
    twitter: "",
  },
  {
    id: 8,
    name: "Sayantana Halder",
    image: "",
    role: "Social",
    linedin: "",
    twitter: "",
  },
  {
    id: 9,
    name: "Sneha Roy",
    image: "",
    role: "Documentation",
    linedin: "",
    twitter: "",
  },
  {
    id: 10,
    name: "Soumyajit",
    image: "",
    role: "Tech Support",
    linedin: "",
    twitter: "",
  },
  {
    id: 11,
    name: "Tapendu",
    image: "",
    role: "Tech Support",
    linedin: "",
    twitter: "",
  },
];
